### ISSUE TITLE
Add config file

### ISSUE THREAD

**Issue by biosafetylvl5** [biosafetylvl5/brassy#7]
Config file with be in yaml, and look like this:

``` yaml
prefix_file:
suffix_file:
template_write_path:
color:
quiet:
```
